name = "choco"
type = "javascript"

account_id = "b7624c46ee3377d0b12e2bf893c00685"
site = {bucket = "./site/dist"}
workers_dev = true

compatibility_date = "2022-02-06"
compatibility_flags = []

[build]
command = "node scripts/build.js production"
[build.upload]
format = "modules"
main = "./index.mjs"

[env.development.build]
command = "node scripts/build.js development"
[env.development.build.upload]
format = "modules"
main = "./index.mjs"

[miniflare]
cache_persist = true
durable_objects_persist = true
global_async_io = true
kv_persist = true

[[kv_namespaces]]
binding = "TAGS"
id = "64a1407445f842ac977d021ec62cf2f5"